### ISSUE TITLE
Error: Cannot find plugin.xml for plugin "needs". Please try adding it again.

### ISSUE THREAD

**Issue by globules-io** [EddyVerbruggen/HealthKit#108]
cordova plugin add com.telerik.plugins.healthkit --variable HEALTH_READ_PERMISSION='App needs read access to health kit' --variable HEALTH_WRITE_PERMISSION='App needs write access to health kit'
Adding com.telerik.plugins.healthkit to package.json
Saved plugin info for "com.telerik.plugins.healthkit" to config.xml
Error: Cannot find plugin.xml for plugin "needs". Please try adding it again.

Cordova 7.1

**Comment by EddyVerbruggen** [comment]
Odd. Can you try double quotes instead of single for those variables?

**Comment by globules-io** [comment]
Yup it worked.

**Comment by EddyVerbruggen** [comment]
That's on Cordova then.
